"""add subject_no to students

Revision ID: 2ea69cf40d8e
Revises: 9c1a2d4f7b11
Create Date: 2026-04-09 01:18:26.113040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '2ea69cf40d8e'
down_revision = '9c1a2d4f7b11'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = {column['name'] for column in inspector.get_columns('students')}

    if 'subject_no' not in existing_columns:
        with op.batch_alter_table('students', schema=None) as batch_op:
            batch_op.add_column(sa.Column('subject_no', sa.String(length=100), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('subject_no')

    # ### end Alembic commands ###
